/* This file was generated by SableCC (http://www.sablecc.org/). */

package de.urszeidler.jact.model.applicationParser.analysis;

import de.urszeidler.jact.model.applicationParser.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object in);
    Object getOut(Node node);
    void setOut(Node node, Object out);

    void caseStart(Start node);
    void caseAApp(AApp node);
    void caseACommaparalistParalist(ACommaparalistParalist node);
    void caseACurrparalistParalist(ACurrparalistParalist node);
    void caseAEmptyParalist(AEmptyParalist node);
    void caseACommaparalist(ACommaparalist node);
    void caseACurrparalist(ACurrparalist node);
    void caseASpara(ASpara node);
    void caseACparaSpara(ACparaSpara node);
    void caseADparaSpara(ADparaSpara node);
    void caseAParaSpara(AParaSpara node);
    void caseACpara(ACpara node);
    void caseADpara(ADpara node);
    void caseAStringLitPara(AStringLitPara node);
    void caseAUrlPara(AUrlPara node);
    void caseADialstrPara(ADialstrPara node);
    void caseAPara(APara node);
    void caseANumberPara(ANumberPara node);

    void caseTBlank(TBlank node);
    void caseTUrl(TUrl node);
    void caseTDialstr(TDialstr node);
    void caseTIdentifier(TIdentifier node);
    void caseTNumber(TNumber node);
    void caseTStringLit(TStringLit node);
    void caseTRPar(TRPar node);
    void caseTLPar(TLPar node);
    void caseTROp(TROp node);
    void caseTLOp(TLOp node);
    void caseTStsep(TStsep node);
    void caseTComma(TComma node);
    void caseTDoublep(TDoublep node);
    void caseTSep(TSep node);
    void caseEOF(EOF node);
}
