/* This file was generated by SableCC (http://www.sablecc.org/). */

package de.urszeidler.jact.model.applicationParser.node;

import java.util.*;
import de.urszeidler.jact.model.applicationParser.analysis.*;

public final class ACparaSpara extends PSpara
{
    private PCpara _cpara_;

    public ACparaSpara()
    {
    }

    public ACparaSpara(
        PCpara _cpara_)
    {
        setCpara(_cpara_);

    }
    public Object clone()
    {
        return new ACparaSpara(
            (PCpara) cloneNode(_cpara_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACparaSpara(this);
    }

    public PCpara getCpara()
    {
        return _cpara_;
    }

    public void setCpara(PCpara node)
    {
        if(_cpara_ != null)
        {
            _cpara_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _cpara_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_cpara_);
    }

    void removeChild(Node child)
    {
        if(_cpara_ == child)
        {
            _cpara_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_cpara_ == oldChild)
        {
            setCpara((PCpara) newChild);
            return;
        }

    }
}
