/* This file was generated by SableCC (http://www.sablecc.org/). */

package de.urszeidler.jact.model.applicationParser.node;

import java.util.*;
import de.urszeidler.jact.model.applicationParser.analysis.*;

public final class ACurrparalist extends PCurrparalist
{
    private TLPar _lPar_;
    private final LinkedList _spara_ = new TypedLinkedList(new Spara_Cast());
    private TRPar _rPar_;

    public ACurrparalist()
    {
    }

    public ACurrparalist(
        TLPar _lPar_,
        List _spara_,
        TRPar _rPar_)
    {
        setLPar(_lPar_);

        {
            this._spara_.clear();
            this._spara_.addAll(_spara_);
        }

        setRPar(_rPar_);

    }
    public Object clone()
    {
        return new ACurrparalist(
            (TLPar) cloneNode(_lPar_),
            cloneList(_spara_),
            (TRPar) cloneNode(_rPar_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACurrparalist(this);
    }

    public TLPar getLPar()
    {
        return _lPar_;
    }

    public void setLPar(TLPar node)
    {
        if(_lPar_ != null)
        {
            _lPar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _lPar_ = node;
    }

    public LinkedList getSpara()
    {
        return _spara_;
    }

    public void setSpara(List list)
    {
        _spara_.clear();
        _spara_.addAll(list);
    }

    public TRPar getRPar()
    {
        return _rPar_;
    }

    public void setRPar(TRPar node)
    {
        if(_rPar_ != null)
        {
            _rPar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _rPar_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_lPar_)
            + toString(_spara_)
            + toString(_rPar_);
    }

    void removeChild(Node child)
    {
        if(_lPar_ == child)
        {
            _lPar_ = null;
            return;
        }

        if(_spara_.remove(child))
        {
            return;
        }

        if(_rPar_ == child)
        {
            _rPar_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_lPar_ == oldChild)
        {
            setLPar((TLPar) newChild);
            return;
        }

        for(ListIterator i = _spara_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(_rPar_ == oldChild)
        {
            setRPar((TRPar) newChild);
            return;
        }

    }

    private class Spara_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PSpara node = (PSpara) o;

            if((node.parent() != null) &&
                (node.parent() != ACurrparalist.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != ACurrparalist.this))
            {
                node.parent(ACurrparalist.this);
            }

            return node;
        }
    }
}
