/* This file was generated by SableCC (http://www.sablecc.org/). */

package de.urszeidler.jact.model.applicationParser.node;

import java.util.*;
import de.urszeidler.jact.model.applicationParser.analysis.*;

public final class ACurrparalistParalist extends PParalist
{
    private PCurrparalist _currparalist_;

    public ACurrparalistParalist()
    {
    }

    public ACurrparalistParalist(
        PCurrparalist _currparalist_)
    {
        setCurrparalist(_currparalist_);

    }
    public Object clone()
    {
        return new ACurrparalistParalist(
            (PCurrparalist) cloneNode(_currparalist_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACurrparalistParalist(this);
    }

    public PCurrparalist getCurrparalist()
    {
        return _currparalist_;
    }

    public void setCurrparalist(PCurrparalist node)
    {
        if(_currparalist_ != null)
        {
            _currparalist_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _currparalist_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_currparalist_);
    }

    void removeChild(Node child)
    {
        if(_currparalist_ == child)
        {
            _currparalist_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_currparalist_ == oldChild)
        {
            setCurrparalist((PCurrparalist) newChild);
            return;
        }

    }
}
