/* This file was generated by SableCC (http://www.sablecc.org/). */

package de.urszeidler.jact.model.applicationParser.node;

import java.util.*;
import de.urszeidler.jact.model.applicationParser.analysis.*;

public final class ADialstrPara extends PPara
{
    private TDialstr _dialstr_;

    public ADialstrPara()
    {
    }

    public ADialstrPara(
        TDialstr _dialstr_)
    {
        setDialstr(_dialstr_);

    }
    public Object clone()
    {
        return new ADialstrPara(
            (TDialstr) cloneNode(_dialstr_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADialstrPara(this);
    }

    public TDialstr getDialstr()
    {
        return _dialstr_;
    }

    public void setDialstr(TDialstr node)
    {
        if(_dialstr_ != null)
        {
            _dialstr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _dialstr_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_dialstr_);
    }

    void removeChild(Node child)
    {
        if(_dialstr_ == child)
        {
            _dialstr_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_dialstr_ == oldChild)
        {
            setDialstr((TDialstr) newChild);
            return;
        }

    }
}
