/* This file was generated by SableCC (http://www.sablecc.org/). */

package de.urszeidler.jact.model.applicationParser.node;

import java.util.*;
import de.urszeidler.jact.model.applicationParser.analysis.*;

public final class ADparaSpara extends PSpara
{
    private PDpara _dpara_;

    public ADparaSpara()
    {
    }

    public ADparaSpara(
        PDpara _dpara_)
    {
        setDpara(_dpara_);

    }
    public Object clone()
    {
        return new ADparaSpara(
            (PDpara) cloneNode(_dpara_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADparaSpara(this);
    }

    public PDpara getDpara()
    {
        return _dpara_;
    }

    public void setDpara(PDpara node)
    {
        if(_dpara_ != null)
        {
            _dpara_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _dpara_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_dpara_);
    }

    void removeChild(Node child)
    {
        if(_dpara_ == child)
        {
            _dpara_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_dpara_ == oldChild)
        {
            setDpara((PDpara) newChild);
            return;
        }

    }
}
