/* This file was generated by SableCC (http://www.sablecc.org/). */

package de.urszeidler.jact.model.applicationParser.node;

import java.util.*;
import de.urszeidler.jact.model.applicationParser.analysis.*;

public final class ADpara extends PDpara
{
    private PPara _para_;
    private TDoublep _doublep_;

    public ADpara()
    {
    }

    public ADpara(
        PPara _para_,
        TDoublep _doublep_)
    {
        setPara(_para_);

        setDoublep(_doublep_);

    }
    public Object clone()
    {
        return new ADpara(
            (PPara) cloneNode(_para_),
            (TDoublep) cloneNode(_doublep_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADpara(this);
    }

    public PPara getPara()
    {
        return _para_;
    }

    public void setPara(PPara node)
    {
        if(_para_ != null)
        {
            _para_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _para_ = node;
    }

    public TDoublep getDoublep()
    {
        return _doublep_;
    }

    public void setDoublep(TDoublep node)
    {
        if(_doublep_ != null)
        {
            _doublep_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _doublep_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_para_)
            + toString(_doublep_);
    }

    void removeChild(Node child)
    {
        if(_para_ == child)
        {
            _para_ = null;
            return;
        }

        if(_doublep_ == child)
        {
            _doublep_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_para_ == oldChild)
        {
            setPara((PPara) newChild);
            return;
        }

        if(_doublep_ == oldChild)
        {
            setDoublep((TDoublep) newChild);
            return;
        }

    }
}
