/* This file was generated by SableCC (http://www.sablecc.org/). */

package de.urszeidler.jact.model.applicationParser.node;

import java.util.*;
import de.urszeidler.jact.model.applicationParser.analysis.*;

public final class AEmptyParalist extends PParalist
{

    public AEmptyParalist()
    {
    }
    public Object clone()
    {
        return new AEmptyParalist();
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEmptyParalist(this);
    }

    public String toString()
    {
        return "";
    }

    void removeChild(Node child)
    {
    }

    void replaceChild(Node oldChild, Node newChild)
    {
    }
}
