/* This file was generated by SableCC (http://www.sablecc.org/). */

package de.urszeidler.jact.model.applicationParser.node;

import java.util.*;
import de.urszeidler.jact.model.applicationParser.analysis.*;

public final class AParaSpara extends PSpara
{
    private PPara _para_;

    public AParaSpara()
    {
    }

    public AParaSpara(
        PPara _para_)
    {
        setPara(_para_);

    }
    public Object clone()
    {
        return new AParaSpara(
            (PPara) cloneNode(_para_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAParaSpara(this);
    }

    public PPara getPara()
    {
        return _para_;
    }

    public void setPara(PPara node)
    {
        if(_para_ != null)
        {
            _para_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _para_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_para_);
    }

    void removeChild(Node child)
    {
        if(_para_ == child)
        {
            _para_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_para_ == oldChild)
        {
            setPara((PPara) newChild);
            return;
        }

    }
}
