/* This file was generated by SableCC (http://www.sablecc.org/). */

package de.urszeidler.jact.model.applicationParser.node;

import java.util.*;
import de.urszeidler.jact.model.applicationParser.analysis.*;

public final class AUrlPara extends PPara
{
    private TUrl _url_;

    public AUrlPara()
    {
    }

    public AUrlPara(
        TUrl _url_)
    {
        setUrl(_url_);

    }
    public Object clone()
    {
        return new AUrlPara(
            (TUrl) cloneNode(_url_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAUrlPara(this);
    }

    public TUrl getUrl()
    {
        return _url_;
    }

    public void setUrl(TUrl node)
    {
        if(_url_ != null)
        {
            _url_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _url_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_url_);
    }

    void removeChild(Node child)
    {
        if(_url_ == child)
        {
            _url_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_url_ == oldChild)
        {
            setUrl((TUrl) newChild);
            return;
        }

    }
}
