/* This file was generated by SableCC (http://www.sablecc.org/). */

package de.urszeidler.jact.model.applicationParser.node;

import de.urszeidler.jact.model.applicationParser.analysis.*;

public final class Start extends Node
{
    private PApp _pApp_;
    private EOF _eof_;

    public Start()
    {
    }

    public Start(
        PApp _pApp_,
        EOF _eof_)
    {
        setPApp(_pApp_);
        setEOF(_eof_);
    }

    public Object clone()
    {
        return new Start(
            (PApp) cloneNode(_pApp_),
            (EOF) cloneNode(_eof_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseStart(this);
    }

    public PApp getPApp()
    {
        return _pApp_;
    }

    public void setPApp(PApp node)
    {
        if(_pApp_ != null)
        {
            _pApp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _pApp_ = node;
    }

    public EOF getEOF()
    {
        return _eof_;
    }

    public void setEOF(EOF node)
    {
        if(_eof_ != null)
        {
            _eof_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _eof_ = node;
    }

    void removeChild(Node child)
    {
        if(_pApp_ == child)
        {
            _pApp_ = null;
            return;
        }

        if(_eof_ == child)
        {
            _eof_ = null;
            return;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_pApp_ == oldChild)
        {
            setPApp((PApp) newChild);
            return;
        }

        if(_eof_ == oldChild)
        {
            setEOF((EOF) newChild);
            return;
        }
    }

    public String toString()
    {
        return "" +
            toString(_pApp_) +
            toString(_eof_);
    }
}
