/* This file was generated by SableCC (http://www.sablecc.org/). */

package de.urszeidler.jact.model.applicationParser.node;

import de.urszeidler.jact.model.applicationParser.analysis.*;

public final class TDoublep extends Token
{
    public TDoublep()
    {
        super.setText(":");
    }

    public TDoublep(int line, int pos)
    {
        super.setText(":");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TDoublep(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTDoublep(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TDoublep text.");
    }
}
