/* This file was generated by SableCC (http://www.sablecc.org/). */

package de.urszeidler.jact.model.applicationParser.node;

import de.urszeidler.jact.model.applicationParser.analysis.*;

public final class TLOp extends Token
{
    public TLOp()
    {
        super.setText("[");
    }

    public TLOp(int line, int pos)
    {
        super.setText("[");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TLOp(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTLOp(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TLOp text.");
    }
}
