/* This file was generated by SableCC (http://www.sablecc.org/). */

package de.urszeidler.jact.model.applicationParser.node;

import de.urszeidler.jact.model.applicationParser.analysis.*;

public final class TROp extends Token
{
    public TROp()
    {
        super.setText("]");
    }

    public TROp(int line, int pos)
    {
        super.setText("]");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TROp(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTROp(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TROp text.");
    }
}
