/* This file was generated by SableCC (http://www.sablecc.org/). */

package de.urszeidler.jact.model.applicationParser.node;

import de.urszeidler.jact.model.applicationParser.analysis.*;

public final class TStsep extends Token
{
    public TStsep()
    {
        super.setText("\'");
    }

    public TStsep(int line, int pos)
    {
        super.setText("\'");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TStsep(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTStsep(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TStsep text.");
    }
}
