/* This file was generated by SableCC (http://www.sablecc.org/). */

package de.urszeidler.jact.model.applicationParser.node;

import de.urszeidler.jact.model.applicationParser.analysis.*;

public final class TUrl extends Token
{
    public TUrl(String text)
    {
        setText(text);
    }

    public TUrl(String text, int line, int pos)
    {
        setText(text);
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TUrl(getText(), getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTUrl(this);
    }
}
