/* This file was generated by SableCC (http://www.sablecc.org/). */

package de.urszeidler.jact.model.applicationParser.parser;

import de.urszeidler.jact.model.applicationParser.node.*;
import de.urszeidler.jact.model.applicationParser.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    public void caseTUrl(TUrl node)
    {
        index = 0;
    }

    public void caseTDialstr(TDialstr node)
    {
        index = 1;
    }

    public void caseTIdentifier(TIdentifier node)
    {
        index = 2;
    }

    public void caseTNumber(TNumber node)
    {
        index = 3;
    }

    public void caseTStringLit(TStringLit node)
    {
        index = 4;
    }

    public void caseTRPar(TRPar node)
    {
        index = 5;
    }

    public void caseTLPar(TLPar node)
    {
        index = 6;
    }

    public void caseTROp(TROp node)
    {
        index = 7;
    }

    public void caseTLOp(TLOp node)
    {
        index = 8;
    }

    public void caseTStsep(TStsep node)
    {
        index = 9;
    }

    public void caseTComma(TComma node)
    {
        index = 10;
    }

    public void caseTDoublep(TDoublep node)
    {
        index = 11;
    }

    public void caseTSep(TSep node)
    {
        index = 12;
    }

    public void caseEOF(EOF node)
    {
        index = 13;
    }
}
